### ISSUE TITLE
Not compatible with Sierra?

### ISSUE THREAD

**Issue by tollie** [dgraham/Ka-Block#103]
I'm confused by the Mac app requiring High Sierra. Is there a particular reason, or is the version requirement mistakenly set?

In the past, I've downloaded (from here) and manually installed KaBlock on Sierra, with no apparent issues.

Thanks in advance.

**Comment by dgraham** [comment]
Apple changed how extensions are distributed in High Sierra. Extensions are now available from the [Mac App Store](
https://itunes.apple.com/us/app/ka-block/id1335413823?mt=12) rather than the old Safari Extensions Gallery.

For prior versions of macOS, you can still download and install the `safariextz` file from the Ka-Block! [3.0 release](https://github.com/dgraham/Ka-Block/releases/tag/v3.0). I'm not sure if this works anymore on older macOS versions with the new Safari 12 release, though. The Mac App Store might be required.

**Comment by tollie** [comment]
>  I'm not sure if this works anymore on older macOS versions with the new Safari 12 release, though. The Mac App Store might be required.

What was my experience. And when I was running Sierra, this effectively shut me out of Ka-Block! For other reasons, I risked it and upgraded my old MBA to Mojave (pleasantly surprised to not see a significant performance hit), so this is no longer an issue for me. But...

My recommendation would be to modify the app so that it doesn't unnecessarily declare that it requires 10.13 or higher, as it's compatible with at least 10.12.

I'm not very familiar with modern Mac programming, or Github for that matter, but I believe the version requirement is [here](https://github.com/dgraham/Ka-Block/blob/master/Ka-Block/macOS/Info.plist) — LSMinimumSystemVersion which looks at $(MACOSX_DEPLOYMENT_TARGET).

Thanks.
