### ISSUE TITLE
Monoprice product variation links don't work

### ISSUE THREAD

**Issue by timkingman** [dgraham/Ka-Block#105]
On any Monoprice product page, like
https://www.monoprice.com/product?c_id=102&cp_id=10232&cs_id=1023205&p_id=34238&seq=1&format=2
there are multiple variations like length and color. Clicking on one of these brings up an overlay and loading spinner, then updates the page, image, and price, and the overlay disappears. With Ka-Block enabled, the overlay and spinner appear, sometimes the page updates, but the overlay never disappears.
I'm sure I've seen this with other blockers, but Ka-Block doesn't have a whitelist, so I need to reload without content blockers every time.

**Comment by dgraham** [comment]
This is caused by blocking a third-party Adobe behavioral tracking script.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.

You can temporarily disable the content blocking extension by long-pressing on the Reload button. And you can disable it for individual websites in Safari > Preferences > Websites > Content Blockers.
