### ISSUE TITLE
Slickdeals.net deals being blocked

### ISSUE THREAD

**Issue by cashxx** [dgraham/Ka-Block#107]
Started killing the posts on slickdeals.net all of a sudden.  Running version 3.2 from MAS.

<img width="1400" alt="screen shot 2018-10-25 at 11 09 32 pm" src="https://user-images.githubusercontent.com/1854255/47542374-19e14100-d8ab-11e8-9ef1-ec369c1e0ca0.png">
<img width="1429" alt="screen shot 2018-10-25 at 11 09 42 pm" src="https://user-images.githubusercontent.com/1854255/47542375-19e14100-d8ab-11e8-9881-4fe2aa47bfaf.png">

**Comment by dgraham** [comment]
It's possible the site's rendering was dependent on third-party JavaScript that is blocked from running because it's a cross-site behavioral tracker.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.

You can temporarily disable the content blocking extension by long-pressing on the Reload button. And you can disable it for individual websites in Safari > Preferences > Websites > Content Blockers.

This site renders with content blockers enabled now. I also added a third-party tracking domain to the filter list in 2bfbcd5c.
