### ISSUE TITLE
sfgate appears empty

### ISSUE THREAD

**Issue by fgiraffe** [dgraham/Ka-Block#109]
With Ka-Block, the site sfgate.com is very broken and erratic. Often it will load OK after 20-30 seconds, but frequently all headlines appear as below. Site loads in 2-3 seconds without Ka-Block. 

<img width="1366" alt="screen shot 2018-11-11 at 12 01 58 pm" src="https://user-images.githubusercontent.com/1637872/48315932-8a29db00-e5aa-11e8-9ccb-01ca8f48d8ea.png">

**Comment by dgraham** [comment]
It's possible the site's rendering was dependent on third-party JavaScript that is blocked from running because it's a cross-site behavioral tracker.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.

The site loads with content blockers now. I also added a couple tracking domains from this site to the filter list in a368d50b.
