### ISSUE TITLE
prevents loading rogers.com

### ISSUE THREAD

**Issue by nhooyr** [dgraham/Ka-Block#120]
Can't load rogers.com with the extension enabled.

Version 3.2

**Comment by nhooyr** [comment]
<img width="1953" alt="screen shot 2019-03-03 at 3 11 33 pm" src="https://user-images.githubusercontent.com/10180857/53701007-a2766d80-3dc6-11e9-9997-f7204ba01071.png">

Just see that forever.

**Comment by builtbyjordan** [comment]
I was experiencing the same thing but now it seems to work. Still same version 3.2. Have you given it another try?

**Comment by dgraham** [comment]
It's possible the site's rendering was dependent on scripts loaded via third-party JavaScript that is blocked from running because it's a cross-site behavioral tracker.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.

This site loads for me now despite blocking a few third-party tracking scripts.

**Comment by elvey** [comment]
I just had the same experience with https://feedbackassistant.apple.com - it wouldn't load (reloaded a few times, IIRC, no dice), so I tried disabling content blockers, and it would load.  And after I re-enabled the content blockers, it would continue to load.   May be worth making a FAQ.   (I had included closed cases when I scanned to see if it my issue was a common/how to proceed, and found this case.)
