### ISSUE TITLE
Google Optimize experiments load 4s slower with Ka-Block

### ISSUE THREAD

**Issue by fulldecent** [dgraham/Ka-Block#125]
# Test case

Example page: https://www.mimeo.com/products/

# Expected outcome

Page renders immediately

# Actual outcome

Page renders after 4-second delay

# Discussion

Here is how a web page using Google Optimize works when configured with default settings:

1. Stop rendering the page (keep everything blank)
1. Create a timer that fires in 4 seconds (and jumps to step 5)
1. Request to load experiment information from Google Optimize
1. Use Google Optimize experiment data to change the page
1. Disable the timer
1. Render the page

When not using Ka-Block! all of this happens in approximately 250ms. But when Ka-Block is installed, step 4 never happens and the web page is only viewable after 4 seconds.

A significant number of web pages in the wild use Google Optimize with default settings.

At our company we change the "async-hide" setting from 4000ms to 800ms to reduce the pain of customers using Ka-Block.

**Comment by dgraham** [comment]
Thanks for the detailed description. This is the expected behavior when a site's rendering is dependent on third-party JavaScript that is blocked from running because it's a cross-site behavioral tracker.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.
