### ISSUE TITLE
ssrn.com now blocking ka-block

### ISSUE THREAD

**Issue by mnot** [dgraham/Ka-Block#159]
In the last ~day, ssrn.com no longer allows access when ka-block is turned on, no matter whether the user is logged in.

**Comment by dgraham** [comment]
Some sites track when third-party scripts fail to load as a way of detecting content blocking extensions. Sometimes a poorly-written site just breaks when a third-party script fails, which can also be caused by network failure.

You can use Safari's option to load the site with content blocking extensions disabled, but there isn't anything the extension itself can do to help.
