### ISSUE TITLE
Compiled blocker list JSON format

### ISSUE THREAD

**Issue by josh** [dgraham/Ka-Block#16]
The current blocker list is simply stored as a single JSON as Safari and iOS expects to load.

Though, I'm thinking we could organize our rules in a more developer friendly way.

## Proposal

A directory of rules with one rule per file.

```
$ cat rules/ads/doubleclick.json
{
  "trigger": {
    "url-filter": "^https?:/+([^/:]+\\.)?doubleclick\\.net[:/]",
    "url-filter-is-case-sensitive": true,
    "load-type": ["third-party"]
  },
  "action": {
    "type": "block"
  }
}
```

**Cons**

* No plain `blockerList.json` is checked into git to be easily downloaded
* Requires additional build tooling

**Pros**

* Git diff friendly way to add new rules. Two PRs adding new rules will more likely apply cleanly.
* Consistently sorted. We don't need to enforce any rules about what order to append rules. Just add a file.
* Option for categorization. We can add nested directories to categorize ads, trackers, social, etc.
* Potential for turn on/off certain rules or categorizes. If we decide to support categories, they can be built into separate rule sets rather than one huge one.

**Variations**

* Implement custom loading in app code rather than build script.
* Invent even more custom rule format. Maybe its just a file like `doubleclick.blockaction` with the contents `^https?:/+([^/:]+\\.)?doubleclick\\.net[:/]`. Could reduce repetition of settings like `url-filter-is-case-sensitive`.

-
To: @dgraham

**Comment by dgraham** [comment]
This is interesting. One of the downsides of the JSON file format is that we lost the plain list of domains with some post processing in JS to turn them into regexes. Adding a new domain used to be a simple entry in an array. Now the workflow is: open JSON file, copy a similar rule, navigate to correct alphabetical position in the list, paste, modify.

The benefit is that the JSON format is much more flexible and allows blocking more than just domains.

> No plain filters.json is checked into git to be easily downloaded

The iOS Xcode project references this file from the OS X extension. Will the reference continue to work if the file is generated rather than always present?

> Requires additional build tooling

I think this is the biggest downside. If it's a simple bash script or Makefile, maybe using [jq](https://github.com/stedolan/jq), it might be ok. If we venture into a complex Ruby or JS toolchain, it might not be worth it.

> Option for categorization. We can add nested directories to categorize ads, trackers, social, etc.

I haven't found ads and trackers to be separate categories. Third-party ads are so intertwined with behavioral tracking, using cookies and query parameters, that one cannot be blocked without the other.

> Potential for turn on/off certain rules or categorizes. 

A few categories we might add are:

- Social sharing buttons - We don't block these today because it could be considered "breaking" the site, but they do act as trackers. We could add a category to block them or just make a policy decision to include them in the current master block list.
- Social comments - Block third-party comment widgets (Facebook, Disqus, etc) designed for behavioral tracking.
- Web fonts - These are brutal on mobile, destroying page load times. Most of the time I wish I were just reading the page in a built-in font rather than waiting for a Typekit file to load.

> If we decide to support categories, they can be built into separate rule sets rather than one huge one.

I think this argues for one JSON file per category rather than per rule, like:

- master.json (always on)
- share-buttons.json
- comments.json
- fonts.json

**Comment by josh** [comment]
> I think this argues for one JSON file per category rather than per rule, like:

Sounds fine. That doesn't require any build steps. I'll close this specific issue out.
