### ISSUE TITLE
Why it runs a process on MacOS?

### ISSUE THREAD

**Issue by neutor** [dgraham/Ka-Block#191]
First, thanks a ton!

I found that I have a process running all the time. I thought this is a Content blocker, just supplying block list to Safari. I'd like to not have a 3rd-party process running.
```
$ ps aux
5:46pm   0:00.03  /Applications/Ka-Block!.app/Contents/PlugIns/Ka-Block! Content Blocker macOS.appex/Contents/MacOS/Ka-Block! Content Blocker macOS -AppleLanguages ("en-AU")
```

Cheers!

**Comment by dgraham** [comment]
Safari loads enabled content blocking plugins as an external process. Disabled plugins do not start a process until they are enabled in Safari preferences. In Ka-Block's case, we don't require a process because it really just delivers a block list JSON file to Safari to compile. In the general case, plugins can do more than this and require a running process. There's no way to avoid this as far as I know.
