### ISSUE TITLE
Ka-Block wrecks the formatting for http://www.hubspot.com

### ISSUE THREAD

**Issue by steven-j-klein** [dgraham/Ka-Block#44]
With Ka-Block enabled, formatting on hubspot pages like this one: http://blog.hubspot.com/sales/gmail-keyboard-shortcuts
is so broken as to make the web page unusable.

(Ironically, that page has only a single unobtrusive ad at the bottom of the page.)

Is there any method for whitelisting websites?

**Comment by dgraham** [comment]
This domain, and its subdomains, is in the filter list because it serves third-party tracking scripts. It also serves content for its homepage from subdomains, so those are blocked by the filter.

Long-press on the reload button in Safari and select `Reload without Content Blockers` to view the domain without activating the filter list. There is no preference setting to whitelist individual ad tracking domains.
