### ISSUE TITLE
More carefully targeted filters: welcome?

### ISSUE THREAD

**Issue by floam** [dgraham/Ka-Block#6]
Hi,

I've been following this and working on getting a little suite of my own "curated"/DIY blocks going.

I'm doing this with my nibware and figured this looked like a decent project to contribute to but before I go too crazy I figured I'd check in, as I'm really looking at this from an iOS 9/Safari 9.0 content extension perspective: Philosophically, and practically for performance, where are you guys on ever allowing /any/ connection to a server that harms privacy or the user experience but where it would be more harmful to the user experience to block the domain outright like a HOSTS file than do nothing? I'm a little nervous only seeing action: block here and no exceptions based on resource types. There is a big promise on the README.md that there will "never" be -any- connections to a bad domain. I kind of feel this is likely more important on your older clients where you implemented the blocking yourself and noted performance concerns... which aren't really the same deal going on with the compiled-down json definitions. 

Not interested in trying to get you guys accepting pull requests of my hokey-marokey converted easylist/easyprivacy that barely loads/compiles and I can personally account for about 0% of the original's intent/function/weighted relevance in 2015 for average user for each filter let alone what kind of undefined behavior my json bomb will certainly bring along... Just want to know if it's OK to discriminate by resource types, bad fragments of URLs to block stuff you couldn't with a HOSTS file. Any clarification on the ideal/goals moving forward would be helpful!

Thanks.

**Comment by dgraham** [comment]
> I'm a little nervous only seeing action: block here and no exceptions based on resource types.

After inspecting each of the domains on the block list, there is nothing of value they offer that should be allowed through.

> There is a big promise on the README.md that there will "never" be -any- connections to a bad domain.

I intended this to mean that the extension itself makes zero network connections. Other extensions actually connect to their own servers with a unique ID given to your browser.

So Ka-Block doesn't even connect to a server to download a block list. The list is bundled inside the extension so it never makes a server connection. The new Content Blocker API enforces this constraint at the platform level, so even better!

> I can personally account for about 0% of the original's intent/function/weighted relevance in 2015

This is definitely a goal for Ka-Block!. The "artisanal selection" of blocked domains means that we've personally seen the domain loading third-party tracking scripts or ads on a site. It takes time to investigate each domain, but it's worth it to keep the block list small and relevant.

> discriminate by resource types, bad fragments of URLs

Blocking specific resource types is something we can do with the new Content Blocker API. I haven't found an example of a domain where we would allow cookies but not images, but we're open to resource blocking as needed.

We've chosen to block by domain because they change infrequently and a single rule blocks a wide range of bad behavior on many sites. Blocking by HTML element ID or URL fragment is riskier because they change so frequently. We would evaluate URL fragments on a case-by-case basis, though.

The general goal of Ka-Block! is to prevent *third-party* trackers and ads from loading because those are the most abusive content. First-party ads, served from the same origin of the site, are generally fine. Analyzing the behavior of a site's own visitors helps improve the site itself. And there's really no way to prevent it because they have their server logs.

Third-party tracking, however, violates your privacy by building a profile of behavior across many sites. And it does so by using your own browser against you. This is the behavior the extension is designed to prevent.

Thanks for the questions!
