### ISSUE TITLE
Topping up one's PAYG account on Three UK is blocked

### ISSUE THREAD

**Issue by acrostich** [dgraham/Ka-Block#92]
Unfortunately this is unlikely to be reproducible if you don't have access to a PAYG Three UK account (and/or don't want to risk topping up your account!). The top up process goes to a page (https://www.three.co.uk/New_My3/Top_up?id=My3_TopUpYourAccountLink) where one selects the value of the top up and then clicks on a button labelled 'Proceed with payment.' which does that only if one disables Ka-Block.

Here's the code for that button if it's of any help:
`<div class="top-upSubmitGreenContainer">
		 <button type="button" id="TopupCardAddonFormSubmitButton" class="my3BlueButton14long selectAddonForm" style="background-color: rgb(0, 124, 195);">Proceed with payment.</button>
		</div>`

**Comment by dgraham** [comment]
It's likely that this behavior is loaded via third-party JavaScript that is blocked from running because it's a cross-site behavioral tracker.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.

There isn't much we can do to fix issues like this other than disabling the extension.

You can temporarily disable the content blocking extension by long-pressing on the Reload button. And you can disable it for individual websites in Safari > Preferences > Websites > Content Blockers.
