### ISSUE TITLE
Issues with images on www.commbank.com.au

### ISSUE THREAD

**Issue by iJaffa** [dgraham/Ka-Block#97]
Banner images on www.commbank.com.au are not loading correctly

**Comment by dgraham** [comment]
The images are loaded via third-party JavaScript that is blocked from running because it's a cross-site behavioral tracker.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.

You can temporarily disable the content blocking extension by long-pressing on the Reload button. And you can disable it for individual websites in Safari > Preferences > Websites > Content Blockers.
