### ISSUE TITLE
weather.com

### ISSUE THREAD

**Issue by wcgall** [dgraham/Ka-Block#98]
Animated local radar maps on weather.com get blocked.

**Comment by dgraham** [comment]
This is often caused by site behaviors loaded via third-party JavaScript that is blocked from running because it's a cross-site behavioral tracker.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.

You can temporarily disable the content blocking extension by long-pressing on the Reload button. And you can disable it for individual websites in Safari > Preferences > Websites > Content Blockers.

I couldn't get the animated maps to display in Safari even with Ka-Block! disabled, though. It may just be broken in general.
